### ISSUE TITLE
Error in running usbq

### ISSUE THREAD

**Issue by arshadyab** [CarveSystems/usbq#1]
Hi,
After cloning and installing I am getting the below error. 
$ usbq mitm
    INFO [                 usbq.pm]: Loading plugins: reload, proxy, pcap, decode, encode, lookfor, usbq_hooks
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/usbq", line 11, in <module>
    load_entry_point('usbq==0.1.0', 'console_scripts', 'usbq')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usbq/cli.py", line 128, in mitm
    enabled=ctx.obj['enable_plugin'],
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/usbq/pm.py", line 62, in enable_plugins
    mod = importlib.import_module(pd.mod)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'usbq.plugins'

**Comment by tomasz-grobelny** [comment]
After copying the usbq/plugins directory to appropriate python modules/usbq location you should be able to move forward (install some other modules and run the app).

**Comment by arshadyab** [comment]
Thanks a lot
