### ISSUE TITLE
Error while running "usbq mitm"

### ISSUE THREAD

**Issue by khaleelarya** [CarveSystems/usbq#3]
Team,

Im facing below issue while running "usbq mitm"

root@armhf:~# usbq mitm
    INFO [                 usbq.pm]: Loading plugins: reload, proxy, pcap, decode, encode, lookfor, usbq_hooks
    INFO [      usbq.plugins.proxy]: Device listen to 0.0.0.0:64240
    INFO [      usbq.plugins.proxy]: Host send to 127.0.0.1:64241
    INFO [       usbq.plugins.pcap]: Logging packets to PCAP file usb.pcap
Traceback (most recent call last):
  File "/usr/local/bin/usbq", line 11, in <module>
    load_entry_point('usbq==0.1.0', 'console_scripts', 'usbq')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/usbq-0.1.0-py3.7.egg/usbq/cli.py", line 128, in mitm
    enabled=ctx.obj['enable_plugin'],
  File "/usr/local/lib/python3.7/dist-packages/usbq-0.1.0-py3.7.egg/usbq/pm.py", line 62, in enable_plugins
    mod = importlib.import_module(pd.mod)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/usbq-0.1.0-py3.7.egg/usbq/plugins/lookfor.py", line 4, in <module>
    import usb
ModuleNotFoundError: No module named 'usb'

Regards
khaleel

**Comment by foxmiti** [comment]
Just try sudo pip3 install pyusb
